---
# tasks file for haproxy

- name: rsync haproxy.cfg to /etc/haproxy/
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  notify:
  - restart haproxy
  tags: conf
- name: start haproxy
  service: name=haproxy state=started
  tags: conf
