---
# tasks file for haproxy
- name: copy haproxy.tar to LB server
  copy: src=haproxy-1.7.8.tar.gz  dest=/root/

- name: adduser haproxy
  user: name=haproxy

- name: check haproxy install evn
  shell: "test -f /etc/haproxy/haproxy.cfg"
  register: rc_v
  #if haproxy is installed.so skip it.


- name: install haproxy
#  shell: cd /root/;tar -xzvf haproxy-1.7.8.tar.gz;cd haproxy-1.7.8;make TARGET=linux2628;make install;cp /usr/local/sbin/haproxy /usr/sbin/;cp examples/haproxy.init /etc/rc.d/init.d/haproxy;chmod +x /etc/rc.d/init.d/haproxy;mkdir /etc/haproxy
  script: haproxy_install.sh
  when: '{{ rc_v.rc }} == "1"'
