---
- name: install MySQL-python
  yum: name=MySQL-python  state=present
- name: download wordpress
  command: 'wget -c https://wordpress.org/latest.tar.gz'
  args:
   chdir: "{{wp_srcdir}}"
   creates: "{{wp_srcdir}}/latest.tar.gz"
  register: wp_download_status

- name: create nginx docroot
  file:
   path: "{{ wp_docroot }}"
   state: directory
   owner: "{{ wp_user }}"
   group: "{{ wp_group }}"

- name: extract wordpress
  shell: "tar xzf latest.tar.gz && mv wordpress {{ wp_docroot }}/{{ wp_sitedir }}"
  args:
   chdir: "{{ wp_srcdir }}"
   creates: "{{ wp_docroot }}/{{ wp_sitedir }}"
  when: wp_download_status.rc == 0

- name: chown wordpress to nginx
  file: path=/opt/nginx/html owner=nginx recurse=yes
